<!DOCTYPE html>
<html>
<head>
	<title>Gija-Ngobe Locker Menu</title>
    <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
    <div class="menu-container">
        <!-- Left side menu -->
        <ul class="horizontal-menu">
            <li><a href="Home.php">Home</a></li>
            <li><a href="About.php">About</a></li>
            <li><a href="Contact Details.php">Contact</a></li>
        </ul>

       
        <ul class="right-menu">
            <li><a href="login.php">Login</a></li>
            <li><a href="registration.php">Register</a></li>
        </ul>
    </div>
    <hr>
</body>
</html>
